services:
  python-server:
    container_name: whisperer-python-server
    networks:
      - whisper-network
    build:
      context: .
      dockerfile: apps/python-server/Dockerfile
    working_dir: /app
    volumes:
      - python_data:/app/data
    ports:
      - "8868:8000"
    env_file:
      - ./apps/python-server/.env
#    healthcheck:
#      test: curl -f http://localhost:8000/ || exit 1
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 5s

  web-ui:
    container_name: whisperer-web-ui
    networks:
      - whisper-network
      - web
    build:
      context: .
      dockerfile: apps/web-ui/Dockerfile
#      args:
#        NEXT_PUBLIC_SERVER_ENDPOINT: ${NEXT_PUBLIC_SERVER_ENDPOINT}
#        OPENAPI_ENDPOINT: ${OPENAPI_ENDPOINT}
#    depends_on:
#      python-server:
#        condition: service_healthy
#    environment:
#      - NEXT_PUBLIC_SERVER_ENDPOINT=${NEXT_PUBLIC_SERVER_ENDPOINT}
#      - OPENAPI_ENDPOINT=${OPENAPI_ENDPOINT}
    working_dir: /app/apps/web-ui
    ports:
      - "3567:3000"
    env_file:
      - ./apps/web-ui/.env.production.local

volumes:
  python_data:

networks:
  whisper-network:
    driver: bridge

  web:
    external: true