services:
  python-server:
    container_name: whisperer-python-server
    restart: unless-stopped
    networks:
      - whisper-network
    build:
      context: .
      dockerfile: apps/python-server/Dockerfile
    working_dir: /app
    volumes:
      - python_data:/app/data
    ports:
      - "8868:8000"
    env_file:
      - ./apps/python-server/.env

  web-ui:
    container_name: whisperer-web-ui
    restart: unless-stopped
    networks:
      - whisper-network
    build:
      context: .
      dockerfile: apps/web-ui/Dockerfile
    working_dir: /app/apps/web-ui
    ports:
      - "3567:3000"
    env_file:
      - ./apps/web-ui/.env.production.local

volumes:
  python_data:

networks:
  whisper-network:
    driver: bridge
